-- Seed Data for SkillSetu (MoSPI SIH26101 Demo)

-- Users
-- password_hash values are real PBKDF2-HMAC-SHA256 digests (600,000 iterations,
-- 16-byte random per-user salt) produced by hash_password() in
-- backend/app/auth/dependencies.py. All three demo accounts share the password
-- SkillSetu@2026 but have DIFFERENT hashes, because each row carries its own salt.
-- These replaced the literal placeholders 'demo_hash_official' / _trainer / _admin,
-- which could never verify against any password.
INSERT OR REPLACE INTO users (id, email, password_hash, role) VALUES
('u-official-001', 'official@skillsetu.demo', 'pbkdf2_sha256$600000$f504725fb6fffc95d28fe49871a68ec7$6b5a79aa2be008e311dd1ac3caedf45e2dafd0b08d56b95b3a49d0f8d888a28c', 'OFFICIAL'),
('u-trainer-001', 'trainer@skillsetu.demo', 'pbkdf2_sha256$600000$2f90ed75876bcee391b9b76445ea0ef9$675d4658431a087e2a8e5796b0f00e77d2ef0d41126d22cb08067229befe4bdb', 'TRAINER'),
('u-admin-001', 'admin@skillsetu.demo', 'pbkdf2_sha256$600000$df178df3d02eae925c15409a6d540cc9$b2dd3f8e63da5afa3ae90080dc79252f702f387dbf3f80491502e90adf10487e', 'ADMIN');

-- Profiles
INSERT OR REPLACE INTO profiles (id, user_id, full_name, designation, department, job_role, current_assignment, educational_qualification, previous_trainings, experience_years) VALUES
('p-official-001', 'u-official-001', 'Ananya Sharma', 'Statistical Officer', 'Ministry of Statistics and Programme Implementation (MoSPI DIID)', 'Senior Data Analyst & Field Survey Coordinator', 'National Sample Survey 80th Round (Socio-Economic Survey)', 'M.Sc. Statistics (Delhi University)', '["NSSO Field Enumeration Workshop", "Introduction to R for Official Statistics"]', 6),
('p-trainer-001', 'u-trainer-001', 'Dr. V. K. Rao', 'Senior Faculty', 'National Statistical Systems Training Academy (NSSTA)', 'Lead Instructor - Statistical Inference', 'TPAC Curriculum Advisory & Executive Training', 'Ph.D. Econometrics (ISI Kolkata)', '["Advanced Survey Methodology", "iGOT Content Authoring Certification"]', 14),
('p-admin-001', 'u-admin-001', 'Rajesh Kumar', 'Director & Division Head', 'Data Informatics & Innovation Division (DIID MoSPI)', 'Strategic Capacity Director', 'National Data & Analytics Platform (NDAP) Oversight', 'M.Tech Computer Science & Post-Grad Statistics', '["National E-Governance Leadership Programme", "Public Policy & Data Strategy"]', 18);

-- Competencies across 4 Domains
INSERT OR REPLACE INTO competencies (id, domain, name, description) VALUES
('comp-stat-001', 'Statistical Competencies', 'Statistical Methods & Inference', 'Principles of statistical inference, hypothesis testing, and probability distributions.'),
('comp-stat-002', 'Statistical Competencies', 'Survey Design & Sampling Methods', 'Stratified sampling, cluster sampling, non-sampling errors, and sample weight adjustments.'),
('comp-stat-003', 'Statistical Competencies', 'National Accounts & Price Statistics', 'CPI/WPI computation, Gross Domestic Product estimation, and macroeconomic indicators.'),
('comp-tech-001', 'Technical Competencies', 'Data Analysis & Python/R', 'Exploratory data analysis using Pandas, R, and automated statistical processing.'),
('comp-tech-002', 'Technical Competencies', 'Official Statistics & Data Visualization', 'Standard metadata frameworks, dashboards, GIS mapping, and open data standards.'),
('comp-gov-001', 'Digital Governance', 'Data Privacy & Cybersecurity', 'Government Data Privacy Guidelines, Digital Personal Data Protection Act, and security.'),
('comp-mgr-001', 'Behavioural & Managerial', 'Public Leadership & Communication', 'Project management in statistical surveys, inter-departmental collaboration, and reporting.');

-- Competency taxonomy expansion: 7 -> 24, still inside the same four MoSPI domains.
-- Seven competencies could not represent the subject spread of the Official Statistical
-- System, and the shortage had a second, sharper cost: with only 2 easy / 5 medium /
-- 3 hard approved questions, a 10-question adaptive run exhausted a difficulty band
-- twice and had to serve a substitute level mid-assessment. Subject areas below are
-- the real ones MoSPI and NSSTA train on (PLFS, ASI, IIP, National Accounts, the SDG
-- National Indicator Framework, NDSAP, MeghRaj, the DPDP Act), not invented labels.
INSERT OR REPLACE INTO competencies (id, domain, name, description) VALUES
('comp-stat-004', 'Statistical Competencies', 'Labour & Employment Statistics', 'PLFS design, usual status and current weekly status, unemployment rate, worker population ratio, LFPR.'),
('comp-stat-005', 'Statistical Competencies', 'Agricultural & Rural Statistics', 'Crop area and yield estimation, general crop estimation surveys, land use classification, cost of cultivation.'),
('comp-stat-006', 'Statistical Competencies', 'Industrial & Enterprise Statistics', 'Annual Survey of Industries, Index of Industrial Production, NIC classification, unincorporated enterprise surveys.'),
('comp-stat-007', 'Statistical Competencies', 'SDG Indicators & Monitoring', 'National Indicator Framework, global indicator tiers, data gap assessment, disaggregation requirements.'),
('comp-stat-008', 'Statistical Competencies', 'Data Quality Assurance Frameworks', 'NQAF/DQAF quality dimensions, editing and imputation, non-response adjustment, revision policy.'),
('comp-tech-003', 'Technical Competencies', 'Statistical Software: Stata, SPSS & SAS', 'Applying survey weights and design specifications in statistical packages, reproducible do-files and syntax.'),
('comp-tech-004', 'Technical Competencies', 'Databases & SQL for Official Statistics', 'Normalisation, join semantics, indexing, and set-based aggregation over survey and administrative tables.'),
('comp-tech-005', 'Technical Competencies', 'Big Data & Administrative Data Integration', 'Record linkage, GST and e-way bill data as statistical inputs, coverage versus measurement error.'),
('comp-tech-006', 'Technical Competencies', 'Machine Learning for Official Statistics', 'Automated occupation and product coding, train/test discipline, overfitting, and model transparency duties.'),
('comp-gov-002', 'Digital Governance', 'Digital Signatures & e-Authentication', 'Public key infrastructure, Digital Signature Certificates, IT Act 2000 recognition, Aadhaar-based e-KYC.'),
('comp-gov-003', 'Digital Governance', 'Government Cloud & Infrastructure', 'MeghRaj GI Cloud, empanelled service providers, data localisation, and continuity planning.'),
('comp-gov-004', 'Digital Governance', 'Digital Public Infrastructure & Interoperability', 'API-first design, IndEA reference architecture, open standards, and registry-based service delivery.'),
('comp-gov-005', 'Digital Governance', 'Open Government Data & Data Sharing', 'NDSAP, data.gov.in publishing, microdata anonymisation, and statistical disclosure control.'),
('comp-mgr-002', 'Behavioural & Managerial', 'Survey Operations & Project Management', 'Field supervision, enumerator training, quality control checks, and schedule and budget control.'),
('comp-mgr-003', 'Behavioural & Managerial', 'Ethics & Integrity in Official Statistics', 'UN Fundamental Principles, respondent confidentiality, professional independence, and impartial release.'),
('comp-mgr-004', 'Behavioural & Managerial', 'Change Management & Digital Adoption', 'Managing resistance to new systems, staged rollout, capability building, and adoption measurement.'),
('comp-mgr-005', 'Behavioural & Managerial', 'Stakeholder Coordination & Collaboration', 'Coordination with line ministries and states, data sharing arrangements, and user consultation.');

-- Pre-approved Assessment Questions
-- correct_option is 0-based and is deliberately spread across all four positions.
-- These ten rows previously had correct_option = 1 nine times out of ten, which meant
-- a candidate (or a script) that always picked the second option scored 9/10 without
-- reading anything. shuffle_options() in backend/app/ai/quality.py protects only
-- AI-generated questions; seeded rows are served straight from this file, so the
-- spread has to be built in here. Options were reordered, not reworded.
INSERT OR REPLACE INTO questions (id, document_id, competency_id, question_text, options_json, correct_option, explanation, difficulty, review_status, source_reference) VALUES
('q-001', NULL, 'comp-stat-001', 'In hypothesis testing, what occurs during a Type I error?', '["Accepting a false null hypothesis", "Calculating incorrect sample size", "Rejecting a true null hypothesis", "Using parametric tests on non-normal data"]', 2, 'Type I error occurs when the null hypothesis is true, but is incorrectly rejected. Its probability is the significance level alpha.', 'medium', 'APPROVED', 'MoSPI Manual Ch. 2'),
('q-002', NULL, 'comp-stat-001', 'Which measure of central tendency is least affected by extreme outliers?', '["Arithmetic Mean", "Standard Deviation", "Variance", "Median"]', 3, 'Median is resistant to outliers because it relies on positional rank rather than exact values.', 'easy', 'APPROVED', 'MoSPI Manual Ch. 1'),
('q-003', NULL, 'comp-stat-002', 'In National Sample Survey (NSS) design, why is Stratified Random Sampling primarily preferred?', '["It ensures proportional representation across heterogeneous sub-populations", "It completely eliminates non-sampling errors", "It is cheaper than simple random sampling", "It eliminates the need for sampling weights"]', 0, 'Stratification reduces sampling variance by dividing a population into homogeneous strata and sampling within each.', 'hard', 'APPROVED', 'NSSO Sampling Design Guide'),
('q-004', NULL, 'comp-stat-002', 'What does the design effect (Deff) in complex survey sampling evaluate?', '["The ratio of sampling error to non-sampling error", "The variance under complex sampling relative to simple random sampling", "The cost effectiveness of field enumeration", "The response rate percentage"]', 1, 'Deff measures the ratio of the variance of an estimator under a complex sampling design to the variance under Simple Random Sampling of the same size.', 'hard', 'APPROVED', 'NSSO Sampling Design Guide'),
('q-005', NULL, 'comp-stat-003', 'Which index formula is currently used for computing the Consumer Price Index (CPI) in India?', '["Paasche Price Index", "Fisher Ideal Index", "Laspeyres Price Index", "Marshall-Edgeworth Index"]', 2, 'India CPI uses a modified Laspeyres formula, which holds the base-period consumption basket fixed.', 'medium', 'APPROVED', 'MoSPI Price Statistics Division'),
('q-006', NULL, 'comp-tech-001', 'Which Python library is standard for handling tabular statistical data structures (DataFrames)?', '["NumPy", "SciPy", "Matplotlib", "Pandas"]', 3, 'Pandas provides the primary DataFrame data structure used for tabular statistical analysis in Python.', 'easy', 'APPROVED', 'MoSPI Tech Upskilling Module'),
('q-007', NULL, 'comp-tech-001', 'What is the main advantage of using SQL window functions like ROW_NUMBER() over GROUP BY in statistical queries?', '["Window functions preserve individual row details while computing aggregate metrics", "Window functions always execute faster than GROUP BY", "Window functions can only be used with numeric columns", "GROUP BY removes duplicate primary keys"]', 0, 'Window functions compute aggregated values across a set of rows while keeping the original row identities intact, so detail and aggregate can be read together.', 'medium', 'APPROVED', 'MoSPI Data Management System'),
('q-008', NULL, 'comp-tech-002', 'What is the primary purpose of SDMX (Statistical Data and Metadata eXchange)?', '["To encrypt official survey microdata", "To standardize exchange of statistical data and metadata across national agencies", "To automate field enumeration using GPS", "To compress large census files"]', 1, 'SDMX is an international standard designed to streamline the exchange of statistical data together with its metadata.', 'hard', 'APPROVED', 'UN & MoSPI Metadata Guidelines'),
('q-009', NULL, 'comp-gov-001', 'Under the Digital Personal Data Protection (DPDP) Act, what is required before processing personal survey data?', '["Prior written approval from NITI Aayog", "Biometric verification of all respondents", "Clear, informed consent or a lawful public mandate", "Encryption using 4096-bit keys"]', 2, 'Processing personal data requires the informed consent of the Data Principal, or one of the legitimate uses the Act specifies, such as a statutory function of the State.', 'medium', 'APPROVED', 'Digital Governance Framework'),
('q-010', NULL, 'comp-mgr-001', 'In project management for large-scale field surveys, what does Critical Path Method (CPM) identify?', '["The survey domain with highest non-response rate", "The total financial budget allocation", "The quality control audit frequency", "The sequence of dependent tasks that determines minimum total project duration"]', 3, 'The critical path is the longest chain of dependent tasks, and therefore sets the shortest possible time in which the project can finish.', 'medium', 'APPROVED', 'NSSTA Management Module');

-- Batch A: completes the easy/medium/hard set for the seven original competencies.
-- Every competency now carries at least one question in each band, which is what lets
-- the adaptive ladder step in either direction without running the pool dry.
INSERT OR REPLACE INTO questions (id, document_id, competency_id, question_text, options_json, correct_option, explanation, difficulty, review_status, source_reference) VALUES
('q-011', NULL, 'comp-stat-001', 'A 95% confidence interval for a population mean has been computed from one sample. Which statement interprets it correctly?', '["If the same sampling procedure were repeated many times, about 95% of the intervals so constructed would contain the true mean", "There is a 95% probability that the true mean lies inside this particular computed interval", "95% of the observations in the sample lie inside the interval", "The interval contains 95% of all possible sample means"]', 0, 'The 95% describes the long-run coverage of the procedure, not a probability statement about one fixed interval. Once computed, an interval either contains the parameter or it does not.', 'hard', 'APPROVED', 'MoSPI Manual Ch. 3'),
('q-012', NULL, 'comp-stat-002', 'In survey sampling, what is the sampling frame?', '["The time period over which fieldwork is conducted", "The list or device from which sample units are actually selected", "The set of questions asked to each respondent", "The margin of error accepted by the survey designer"]', 1, 'The sampling frame is the operational list of units from which the sample is drawn. A gap between the frame and the target population causes coverage error, which no increase in sample size can repair.', 'easy', 'APPROVED', 'NSSO Sampling Design Guide'),
('q-013', NULL, 'comp-stat-002', 'Why are sampling weights applied when estimating population totals from NSS data?', '["To reduce the size of the dataset before analysis", "To convert nominal values into real values", "Because units were selected with unequal probabilities, so each responding unit represents a different number of population units", "Because the schedule contained both objective and subjective items"]', 2, 'A weight is essentially the reciprocal of the selection probability, further adjusted for non-response and calibration. Ignoring weights biases estimates towards over-sampled groups.', 'medium', 'APPROVED', 'NSSO Estimation Procedure Manual'),
('q-014', NULL, 'comp-stat-003', 'What does Gross Domestic Product at market prices measure?', '["The total money supply circulating in the economy", "The total income of the central government in a financial year", "The stock of physical capital owned by residents", "The value of all final goods and services produced within the country in a given period"]', 3, 'GDP is a flow of production over a period. Only final goods and services are counted, so that intermediate consumption is not double counted.', 'easy', 'APPROVED', 'National Accounts Statistics Sources and Methods'),
('q-015', NULL, 'comp-stat-003', 'Analysts often attribute a change in year-on-year inflation to a base effect. What does that mean?', '["An unusually high or low index value in the comparison period moves the current inflation rate even when present prices are stable", "The base year weights have been revised, so the index is no longer comparable", "The index has crossed 100 and therefore begins to compound", "Seasonal items have been removed from the consumption basket"]', 0, 'Year-on-year inflation is a ratio to the same month a year earlier, so an abnormal denominator shifts the rate by itself. This is why momentum is read alongside the headline rate.', 'hard', 'APPROVED', 'MoSPI Price Statistics Division'),
('q-016', NULL, 'comp-tech-001', 'In Pandas, why can chained assignment such as df[df.a > 0][''b''] = 1 silently fail to modify the DataFrame?', '["Because boolean masks are not permitted on the left-hand side of an assignment", "Because the first selection may return a copy rather than a view, so the assignment updates a temporary object", "Because the target column must be numeric for assignment to succeed", "Because assignment requires the DataFrame index to be sorted"]', 1, 'Chained indexing creates an intermediate object that may be a copy. The reliable form is a single call, df.loc[df.a > 0, "b"] = 1, which assigns into the original frame.', 'hard', 'APPROVED', 'MoSPI Tech Upskilling Module'),
('q-017', NULL, 'comp-tech-002', 'What is metadata in the context of an official statistical release?', '["The raw responses collected from each household", "The software used to compile the tables", "Information describing the data, such as definitions, coverage, reference period and method of collection", "The list of officials authorised to approve the release"]', 2, 'Metadata is what allows a user to judge whether a figure is fit for their purpose. A number published without its definitions, coverage and reference period cannot be interpreted or compared.', 'easy', 'APPROVED', 'UN & MoSPI Metadata Guidelines'),
('q-018', NULL, 'comp-tech-002', 'A district map is shaded by literacy rate using equal-interval class breaks. What is the main risk?', '["Choropleth maps cannot display rates, only counts", "Equal-interval breaks require the underlying data to be normally distributed", "The map will always understate values in geographically small districts", "If the distribution is skewed, most districts fall into one class and real variation disappears"]', 3, 'The choice of class breaks changes the visual message. For skewed distributions, quantile or natural-breaks classification exposes variation that equal intervals compress into a single shade.', 'medium', 'APPROVED', 'MoSPI Data Visualization Standards'),
('q-019', NULL, 'comp-gov-001', 'What is the purpose of role-based access control in a government data system?', '["Each user can access only the data and functions that their official role requires", "All users share one administrative account so that auditing is simpler", "Passwords are replaced entirely by biometric verification", "Data is encrypted with a different algorithm for each department"]', 0, 'Role-based access control implements least privilege: access follows the duties of the role. This limits the damage from a single compromised account and makes audit trails meaningful.', 'easy', 'APPROVED', 'Digital Governance Framework'),
('q-020', NULL, 'comp-gov-001', 'Under the Digital Personal Data Protection Act 2023, what must a Data Fiduciary do after a personal data breach?', '["Nothing further, provided the data was encrypted at rest", "Give notice of the breach to the Data Protection Board and to each affected Data Principal", "File a police report within twenty-four hours", "Delete all remaining copies of the affected dataset"]', 1, 'The Act obliges a Data Fiduciary to notify the Data Protection Board and every affected Data Principal, in the form and manner prescribed. Encryption reduces harm but does not remove the duty to notify.', 'hard', 'APPROVED', 'DPDP Act 2023'),
('q-021', NULL, 'comp-mgr-001', 'In a written brief for senior management, where should the main finding appear?', '["In an annexure, supported by the full data tables", "After the methodology, so the reader can judge the finding in context", "At the start, with the supporting detail placed after it", "In the conclusion, so that the argument builds towards it"]', 2, 'Executive readers decide from the opening paragraph. Leading with the finding and the recommended action, then supporting it, reduces misreading and respects the reader time budget.', 'easy', 'APPROVED', 'NSSTA Management Module'),
('q-022', NULL, 'comp-mgr-001', 'A scheduled release shows a fall in a headline indicator that contradicts a recent ministry statement. What is the professionally correct course?', '["Postpone the release until the discrepancy has been resolved administratively", "Publish the figure with no commentary and leave users to reconcile it", "Publish only the sub-indicators that agree with the statement", "Publish on the pre-announced date and explain the definitional and methodological reasons the two figures differ"]', 3, 'A pre-announced release calendar and professional independence are core principles of official statistics. The remedy for an apparent contradiction is an explanation of scope, definitions and reference period, not delay or selective publication.', 'hard', 'APPROVED', 'UN Fundamental Principles of Official Statistics');

-- Batch B: the five new Statistical competencies, one question per difficulty band.
INSERT OR REPLACE INTO questions (id, document_id, competency_id, question_text, options_json, correct_option, explanation, difficulty, review_status, source_reference) VALUES
('q-023', NULL, 'comp-stat-004', 'In the Periodic Labour Force Survey, what does the Labour Force Participation Rate measure?', '["The percentage of persons in the population who are either working or seeking work", "The percentage of workers employed in the formal sector", "The percentage of the labour force that is unemployed", "The percentage of the population above the legal working age"]', 0, 'LFPR is the share of the population in the labour force, that is workers plus those seeking or available for work. The unemployment rate is a share of the labour force, not of the population, so the two denominators differ.', 'easy', 'APPROVED', 'PLFS Annual Report - Concepts'),
('q-024', NULL, 'comp-stat-004', 'In PLFS, how does Current Weekly Status differ from Usual Status?', '["Current Weekly Status counts only salaried employment while Usual Status counts all employment", "Current Weekly Status classifies activity over a seven-day reference period while Usual Status uses the preceding 365 days", "Current Weekly Status is collected only in urban areas", "Usual Status excludes any subsidiary economic activity"]', 1, 'The two approaches differ in reference period. A seven-day window captures seasonal and intermittent work that a 365-day classification can absorb into the principal activity.', 'medium', 'APPROVED', 'PLFS Annual Report - Concepts'),
('q-025', NULL, 'comp-stat-004', 'PLFS reports a falling unemployment rate together with a falling LFPR. Why is that a weak signal of improvement?', '["Because the two rates are computed from different samples", "Because the unemployment rate is seasonally adjusted and LFPR is not", "Because people who stop seeking work leave the labour force, lowering the denominator of the unemployment rate without anyone gaining a job", "Because a lower LFPR always indicates higher enrolment in education"]', 2, 'Discouraged withdrawal from the labour force reduces the measured unemployment rate arithmetically. This is exactly why LFPR and the worker population ratio are read alongside the headline rate.', 'hard', 'APPROVED', 'PLFS Annual Report - Concepts'),
('q-026', NULL, 'comp-stat-005', 'How is crop production conventionally estimated in Indian agricultural statistics?', '["By counting the quantity sold in regulated markets", "By dividing rural population by cultivated area", "From satellite imagery alone", "As area under the crop multiplied by the estimated yield per unit area"]', 3, 'Production equals area multiplied by yield. Area comes from land records or area enumeration and yield from crop cutting experiments, so an error in either component propagates into the production estimate.', 'easy', 'APPROVED', 'Agricultural Statistics at a Glance'),
('q-027', NULL, 'comp-stat-005', 'What is the purpose of a crop cutting experiment?', '["To obtain an objective yield estimate by harvesting a randomly located plot of specified size", "To test which crop variety fetches the highest market price", "To verify the ownership of land parcels", "To measure the moisture content required for safe storage"]', 0, 'Crop cutting experiments produce an objective yield estimate from randomly located plots, in preference to a subjective eye estimate made by field staff.', 'medium', 'APPROVED', 'General Crop Estimation Survey Manual'),
('q-028', NULL, 'comp-stat-005', 'In the nine-fold land use classification, net sown area plus area sown more than once gives which aggregate?', '["Cultivable waste", "Gross cropped area", "Net area available for cultivation", "Total geographical area"]', 1, 'Gross cropped area counts each cropping of the same land separately, so it equals net sown area plus the area sown more than once. The ratio of the two is the cropping intensity.', 'hard', 'APPROVED', 'Land Use Statistics Manual'),
('q-029', NULL, 'comp-stat-006', 'What does the Annual Survey of Industries cover?', '["All enterprises in the country, including household units", "Only public sector undertakings", "Registered manufacturing factories covered under the Factories Act", "Only units engaged in export"]', 2, 'ASI is the principal source for registered manufacturing, with a frame drawn from units registered under the Factories Act. Unregistered manufacturing is covered separately through unincorporated enterprise surveys.', 'easy', 'APPROVED', 'ASI Concepts and Definitions'),
('q-030', NULL, 'comp-stat-006', 'What does the Index of Industrial Production measure?', '["The value of industrial output at current prices", "The profitability of the industrial sector", "The number of persons employed in industry", "The change in the volume of production of a basket of industrial items relative to a base period"]', 3, 'IIP is a volume index. It holds base-period weights fixed and tracks quantity relatives, so unlike a value series it is not moved by price change.', 'medium', 'APPROVED', 'IIP Base Revision Report'),
('q-031', NULL, 'comp-stat-006', 'Why is National Industrial Classification coding essential when compiling enterprise statistics?', '["It assigns each unit to a defined economic activity, so aggregates stay comparable across sources and over time", "It determines the tax rate applicable to the enterprise", "It fixes the sampling weight to be used for the unit", "It records the legal ownership structure of the enterprise"]', 0, 'NIC gives a standard activity code. Without a common classification, output from two sources cannot be added or compared, and a change in coding practice shows up as a spurious trend.', 'hard', 'APPROVED', 'National Industrial Classification 2008'),
('q-032', NULL, 'comp-stat-007', 'What is the National Indicator Framework for the Sustainable Development Goals?', '["A ranking of states by SDG performance published each year", "The set of indicators, with defined data sources and nodal ministries, used to monitor SDG progress in India", "The global list of indicators adopted by the United Nations", "A fund allocation formula linked to SDG targets"]', 1, 'The NIF is the domestic monitoring framework. It names each indicator with its data source, periodicity and responsible nodal ministry, which is what makes progress reporting auditable.', 'easy', 'APPROVED', 'SDG National Indicator Framework'),
('q-033', NULL, 'comp-stat-007', 'Many SDG targets require disaggregated reporting. What does that demand of the underlying survey?', '["A shorter schedule, so that response rates rise", "Reporting only at national level in order to protect confidentiality", "Sample size and design sufficient to give reliable estimates for sub-groups such as sex, location and social group", "Annual rather than quinquennial collection in every case"]', 2, 'Leave no one behind requires estimates by sub-group. Disaggregation multiplies the number of estimation domains, and each domain needs enough sample to keep its standard error acceptable.', 'medium', 'APPROVED', 'SDG National Indicator Framework'),
('q-034', NULL, 'comp-stat-007', 'An SDG indicator is classified as Tier II in the global framework. What does that signify?', '["The indicator has been withdrawn from the global framework", "The indicator is reported only by developed countries", "The indicator is conceptually clear and data are already widely available", "The indicator is conceptually clear with an established methodology, but data are not regularly produced by most countries"]', 3, 'Tier classification separates methodological readiness from data availability. Tier II means the method exists but country coverage is thin, which is precisely where statistical capacity building is directed.', 'hard', 'APPROVED', 'UN IAEG-SDG Tier Classification'),
('q-035', NULL, 'comp-stat-008', 'Which of the following is a recognised dimension of statistical data quality?', '["Timeliness", "File size", "Number of authors", "Choice of programming language"]', 0, 'Quality frameworks list dimensions such as relevance, accuracy, timeliness, comparability, coherence and accessibility. An accurate figure published too late to inform the decision has still failed on quality.', 'easy', 'APPROVED', 'UN National Quality Assurance Framework'),
('q-036', NULL, 'comp-stat-008', 'What is imputation in survey data processing?', '["Deleting every record that has any missing value", "Replacing a missing or inconsistent value with a plausible estimate derived by a documented rule", "Rounding published estimates in order to protect confidentiality", "Re-contacting the respondent to obtain the missing value"]', 1, 'Imputation fills gaps by a documented method such as hot-deck or regression imputation, and the imputed status is flagged. Dropping incomplete records instead would bias estimates whenever non-response is not random.', 'medium', 'APPROVED', 'UN National Quality Assurance Framework'),
('q-037', NULL, 'comp-stat-008', 'Why does a statistical office publish a revision policy alongside its estimates?', '["Because revisions are prohibited unless a policy expressly permits them", "To transfer responsibility for errors to the data providers", "Because revisions are an expected consequence of better information arriving later, and a published policy tells users when and why to expect them", "Because a revision policy removes the need to publish provisional estimates at all"]', 2, 'Early estimates trade accuracy for timeliness. A published revision calendar and methodology lets users distinguish routine revision from error, which protects credibility rather than undermining it.', 'hard', 'APPROVED', 'UN National Quality Assurance Framework');

-- Batch C: the four new Technical competencies, one question per difficulty band.
INSERT OR REPLACE INTO questions (id, document_id, competency_id, question_text, options_json, correct_option, explanation, difficulty, review_status, source_reference) VALUES
('q-038', NULL, 'comp-tech-003', 'Why is a saved do-file or syntax file preferred over point-and-click menus in official statistical work?', '["It executes faster on large datasets", "It removes the need for separate data documentation", "It allows more variables to be held in memory", "It records every step, so the analysis can be reproduced and audited later"]', 3, 'Reproducibility is a quality requirement rather than a convenience. A saved script lets a different officer re-run the same estimate months later and obtain the same number, which menu-driven work cannot guarantee.', 'easy', 'APPROVED', 'NSSTA Statistical Computing Module'),
('q-039', NULL, 'comp-tech-003', 'In Stata, what does declaring the survey design with svyset before estimation achieve?', '["Standard errors account for the sampling design, including strata, clusters and weights", "Missing values are imputed automatically", "The dataset is sorted by primary sampling unit", "Point estimates are converted into per capita terms"]', 0, 'Without a design declaration the software assumes simple random sampling and reports standard errors that are usually too small, so confidence intervals appear tighter than the design justifies.', 'medium', 'APPROVED', 'NSSTA Statistical Computing Module'),
('q-040', NULL, 'comp-tech-003', 'An analyst applies frequency weights where probability weights were required. What is the most likely consequence?', '["Point estimates shift but standard errors are unaffected", "Variance estimation is wrong, because the two weight types imply different assumptions about how the data arose", "The estimation command refuses to run", "Only the sample size printed in the output changes"]', 1, 'Frequency weights represent duplicated identical observations; probability weights represent unequal selection probabilities. Substituting one for the other produces variance estimates built on the wrong model even when the point estimate looks plausible.', 'hard', 'APPROVED', 'NSSTA Statistical Computing Module'),
('q-041', NULL, 'comp-tech-004', 'What does a PRIMARY KEY constraint guarantee about a column?', '["The column is stored in sorted order on disk", "The column can hold only numeric values", "Values are unique and not null, so each row can be identified unambiguously", "The column is automatically used as an index by every query"]', 2, 'A primary key enforces uniqueness and non-nullity, which is what allows a row to be referenced reliably from another table.', 'easy', 'APPROVED', 'MoSPI Data Management System'),
('q-042', NULL, 'comp-tech-004', 'A district-wise table is compiled with a LEFT JOIN instead of an INNER JOIN. What changes?', '["Duplicate rows are removed from the result", "The join can execute without an index", "Only rows present in both tables are returned", "Districts with no matching row in the second table are still returned, with nulls in its columns"]', 3, 'An inner join silently drops unmatched districts, which understates coverage. A left join keeps them visible as nulls, so a gap in the data reads as a gap rather than as a district that does not exist.', 'medium', 'APPROVED', 'MoSPI Data Management System'),
('q-043', NULL, 'comp-tech-004', 'Why can COUNT(column) and COUNT(*) return different numbers on the same table?', '["COUNT(column) ignores rows where that column is null, while COUNT(*) counts all rows", "COUNT(*) samples the table once it grows large", "COUNT(column) counts distinct values only", "COUNT(*) excludes rows inserted in the current transaction"]', 0, 'SQL aggregate functions skip nulls. Reporting COUNT(column) as a record count therefore silently reports the completeness of that one column instead of the size of the table.', 'hard', 'APPROVED', 'MoSPI Data Management System'),
('q-044', NULL, 'comp-tech-005', 'What is administrative data in a statistical context?', '["Data generated by statistical offices during survey processing", "Data collected by government bodies as a by-product of running a programme or regulation, later reused for statistics", "Data published in ministry press releases", "Metadata describing survey questionnaires"]', 1, 'Administrative sources such as tax, registration or benefit records are collected to administer a programme, not to measure a population. Reuse is cheap and timely, but definitions and coverage follow the administrative purpose rather than the statistical one.', 'easy', 'APPROVED', 'MoSPI Administrative Data Guidance'),
('q-045', NULL, 'comp-tech-005', 'What is record linkage?', '["Encrypting identifiers before publication", "Storing several datasets within one database schema", "Identifying records in different sources that refer to the same unit, often without a shared unique identifier", "Converting a wide dataset into long format"]', 2, 'Linkage matches entities across sources using attributes such as name, address or date of birth when no common key exists. False matches and missed matches both introduce error, so match quality has to be measured rather than assumed.', 'medium', 'APPROVED', 'MoSPI Administrative Data Guidance'),
('q-046', NULL, 'comp-tech-005', 'GST returns are proposed as a source for turnover statistics. Which limitation matters most for statistical use?', '["The data are updated too frequently to be usable", "GST data cannot be held in a relational database", "The returns contain no monetary values", "Coverage follows the registration threshold and administrative definitions, so units below the threshold are absent and concepts may not match the statistical target"]', 3, 'Large administrative datasets have very low sampling error but potentially large coverage and concept error. Volume does not repair a frame that excludes part of the target population by design.', 'hard', 'APPROVED', 'MoSPI Administrative Data Guidance'),
('q-047', NULL, 'comp-tech-006', 'Why is a dataset split into training and test sets when fitting a model?', '["To estimate how the model performs on data it has not seen", "To reduce the memory needed for fitting", "To ensure both sets have identical distributions", "Because most algorithms cannot process the full dataset at once"]', 0, 'Accuracy measured on the training data is optimistic because the model has already adapted to it. A held-out set gives an honest estimate of performance on new cases.', 'easy', 'APPROVED', 'NSSTA Data Science Module'),
('q-048', NULL, 'comp-tech-006', 'A model that assigns occupation codes to free-text responses reaches 99% accuracy on training data but 71% on held-out data. What does this indicate?', '["The training set was too small for the model to converge", "The model has overfitted, learning noise specific to the training data rather than a general rule", "The held-out data must have been mislabelled", "Accuracy is an inappropriate metric for classification"]', 1, 'A large gap between training and held-out performance is the signature of overfitting. Regularisation, a simpler model, or more varied training data are the usual remedies.', 'medium', 'APPROVED', 'NSSTA Data Science Module'),
('q-049', NULL, 'comp-tech-006', 'Why does a statistical office face a stronger transparency duty than a private firm when using a model to code survey responses?', '["Because statistical offices are barred from using proprietary software", "Because minimum model accuracy is fixed by statute", "Because published official statistics must be explainable and reproducible, so an opaque model would make the resulting figures unauditable", "Because machine learning is less accurate than manual coding in every case"]', 2, 'Official figures carry a duty of methodological transparency. A model whose decisions cannot be documented or reproduced undermines the auditability that official statistics rest on, which is why offices publish coding methods and retain manual review for uncertain cases.', 'hard', 'APPROVED', 'UN Fundamental Principles of Official Statistics');

-- Batch D: the four new Digital Governance competencies, one question per difficulty band.
INSERT OR REPLACE INTO questions (id, document_id, competency_id, question_text, options_json, correct_option, explanation, difficulty, review_status, source_reference) VALUES
('q-050', NULL, 'comp-gov-002', 'Under the Information Technology Act, 2000, what does a digital signature on a released statistical table establish?', '["That the table is encrypted while in transit", "That the table cannot be opened without a password", "That the figures have been checked for arithmetic errors", "That the document came from the named signatory and has not been altered since it was signed"]', 3, 'A digital signature provides authenticity and integrity. It says nothing about confidentiality and nothing about whether the numbers are correct, which is why signing sits at the end of the release process rather than replacing quality checks.', 'easy', 'APPROVED', 'IT Act 2000 Section 3'),
('q-051', NULL, 'comp-gov-002', 'What is the role of a Certifying Authority in India''s Public Key Infrastructure?', '["It issues Digital Signature Certificates that bind a public key to a verified identity", "It stores the private keys of all signatories so they can be recovered", "It encrypts documents on behalf of government departments", "It maintains an archive of every signed document"]', 0, 'A Certifying Authority licensed by the Controller of Certifying Authorities vouches for the link between an identity and a public key. The private key never leaves the holder; if the authority held it, non-repudiation would collapse.', 'medium', 'APPROVED', 'IT Act 2000 Chapter VI'),
('q-052', NULL, 'comp-gov-002', 'An officer''s Digital Signature Certificate expires, while releases signed last year remain in the public domain. What happens to those earlier signatures?', '["They become invalid and the releases must be signed again", "They remain verifiable, because validation checks whether the certificate was valid at the time of signing", "They can be verified only by the Certifying Authority", "They are renewed automatically along with the new certificate"]', 1, 'A trusted timestamp records when the signature was applied, so validity is judged at that moment rather than today. Expiry stops new signatures but does not retroactively void old ones. Revocation following key compromise is a separate case and does affect earlier signatures.', 'hard', 'APPROVED', 'IT Act 2000 Chapter VI'),
('q-053', NULL, 'comp-gov-003', 'What is MeghRaj?', '["A national licence governing the reuse of government datasets", "The e-authentication framework for government portals", "India''s Government Cloud initiative, providing empanelled cloud services to government departments", "The unified payments interface used by ministries"]', 2, 'MeghRaj, the GI Cloud initiative, lets departments consume services from empanelled cloud providers under common security and audit requirements instead of each department procuring and running its own hardware.', 'easy', 'APPROVED', 'MeitY GI Cloud Framework'),
('q-054', NULL, 'comp-gov-003', 'A department hosts its survey portal on empanelled cloud infrastructure. Why does it still remain accountable for data protection?', '["Because empanelment carries no security requirements", "Because cloud providers may not store government data at all", "Because the provider accepts liability only for hardware failure", "Because the department remains the data fiduciary, while the provider processes data on its instructions"]', 3, 'Responsibility is shared: the provider secures the infrastructure, and the department stays answerable for access control, retention and lawful use. Outsourcing hosting does not outsource accountability.', 'medium', 'APPROVED', 'MeitY GI Cloud Framework'),
('q-055', NULL, 'comp-gov-003', 'A statistical portal must stay available through a traffic spike on release day. Which design choice addresses this most directly?', '["Horizontal scaling behind a load balancer, so additional instances absorb the spike", "Increasing the database connection timeout", "Compressing the published tables before upload", "Scheduling the release outside office hours"]', 0, 'A predictable spike is a capacity problem. Extra instances behind a load balancer widen the bottleneck; a longer timeout only makes requests queue for longer, and compression saves bandwidth without adding capacity.', 'hard', 'APPROVED', 'MeitY GI Cloud Framework'),
('q-056', NULL, 'comp-gov-004', 'What does interoperability between two government systems mean?', '["Both run on identical hardware", "They can exchange data and use it meaningfully, because formats and definitions are agreed in advance", "They share a single administrator account", "They were built by the same vendor"]', 1, 'Moving a file across is not enough; the receiving system has to interpret each field the same way the sender did. Agreed schemas and shared code lists are what turn an exchange into usable data.', 'easy', 'APPROVED', 'India Enterprise Architecture Framework'),
('q-057', NULL, 'comp-gov-004', 'Why is an API-based exchange usually preferable to emailing spreadsheets between departments?', '["An API removes the need for access control", "Spreadsheets cannot hold large volumes of data", "An API delivers a defined schema on request, so the consumer always reads current data in a known structure and every call can be logged", "An API guarantees that the underlying data are accurate"]', 2, 'Emailed files create versioned copies that drift, invite manual edits and leave no audit trail. An API keeps a single source of truth, a machine-readable contract and a record of who read what. Accuracy still depends on the source system.', 'medium', 'APPROVED', 'India Enterprise Architecture Framework'),
('q-058', NULL, 'comp-gov-004', 'A shared district code list is revised, but one department continues to use the previous version. What is the most likely effect on a combined national table?', '["Compilation will fail, exposing the problem immediately", "Only the total row is affected", "The effect is confined to district names and does not touch the figures", "Records will silently mis-join or drop, so districts may be double counted or missing while the table still looks complete"]', 3, 'This is a master data problem, and its danger is that nothing errors. Versioned code lists plus a reconciliation count against the known number of districts is the control that makes such a mismatch visible.', 'hard', 'APPROVED', 'India Enterprise Architecture Framework'),
('q-059', NULL, 'comp-gov-005', 'Under the National Data Sharing and Accessibility Policy, how are government datasets classified for sharing?', '["As open, registered or restricted, depending on sensitivity and access conditions", "As draft, final or archived", "As central, state or district", "As free or paid"]', 0, 'NDSAP separates data that can be published openly from data that requires registration and from data that stays restricted. The classification decides the sharing route, so it is settled before publication rather than after.', 'easy', 'APPROVED', 'NDSAP 2012'),
('q-060', NULL, 'comp-gov-005', 'What does describing a published dataset as machine-readable require?', '["That the file is under 10 MB", "That its structure can be parsed programmatically, as with CSV or JSON, rather than needing a human to interpret the layout", "That it is published without metadata", "That it opens in a spreadsheet application"]', 1, 'A scanned table inside a PDF opens perfectly for a human yet has to be re-keyed or put through OCR before a program can use it. Machine readability is a property of structure, not of file size or of whether some application can display the file.', 'medium', 'APPROVED', 'NDSAP 2012'),
('q-061', NULL, 'comp-gov-005', 'A unit-level survey dataset is to be released publicly. Which step is essential before release?', '["Converting the file to a proprietary format so reuse can be controlled", "Removing every continuous variable", "Statistical disclosure control, so no individual respondent can be re-identified from combinations of the remaining variables", "Publishing only aggregate totals, because unit-level release is never permitted"]', 2, 'Dropping name and address is not sufficient, because a rare combination of age, location and occupation can still single out a person. Disclosure control methods such as suppression, coarsening and controlled noise are applied and the residual risk documented. Anonymised unit-level release is permitted once that assessment is done, so the last option overstates the rule.', 'hard', 'APPROVED', 'NDSAP 2012');

-- Batch E: the four new Behavioural/Managerial competencies, one question per difficulty band.
INSERT OR REPLACE INTO questions (id, document_id, competency_id, question_text, options_json, correct_option, explanation, difficulty, review_status, source_reference) VALUES
('q-062', NULL, 'comp-mgr-002', 'What is the purpose of a pilot survey before the main field round?', '["To publish preliminary estimates ahead of the full round", "To reduce the sample size needed for the main round", "To train respondents in answering the questionnaire", "To test the questionnaire, field procedures and timing so problems are found before full-scale fieldwork"]', 3, 'A pilot buys information cheaply. Fixing a confusing question after a hundred thousand interviews is impossible; fixing it after a hundred is routine.', 'easy', 'APPROVED', 'NSS Field Operations Manual'),
('q-063', NULL, 'comp-mgr-002', 'Field supervisors report that one investigator''s interviews average 11 minutes against a round average of 38. What is the appropriate first response?', '["Re-verify a sample of that investigator''s schedules in the field, since the duration suggests entries may not have been collected as prescribed", "Treat the speed as good practice and encourage others to adopt it", "Drop those schedules from the dataset without further checking", "Increase the sample in that district to compensate"]', 0, 'Paradata such as interview duration are a quality signal rather than a productivity score. An outlier triggers verification, and any decision to retain or drop follows the evidence, because silent deletion is itself an unaudited change to the achieved sample.', 'medium', 'APPROVED', 'NSS Field Operations Manual'),
('q-064', NULL, 'comp-mgr-002', 'Fieldwork is running three weeks behind schedule and the release date is fixed. Which trade-off is most defensible?', '["Allow investigators to complete the remaining schedules from memory to save travel time", "Publish on time with a documented lower response rate and a clear caveat, or defer the release with a public explanation", "Substitute easier-to-reach households for the sampled ones to close the gap quickly", "Impute the missing districts and publish without noting the change in method"]', 1, 'The two honest routes are publish with disclosure or reschedule with an explanation. Convenience substitution breaks the probability design, and undocumented imputation is worse than a late release because users cannot tell that the basis of the figure changed.', 'hard', 'APPROVED', 'NSS Field Operations Manual'),
('q-065', NULL, 'comp-mgr-003', 'An officer is asked by an acquaintance for the name of a business that responded to a survey. What is the correct response?', '["Share it, since the survey is a government activity", "Share it only if the acquaintance signs an undertaking", "Refuse, because identifiable respondent information may be used only for statistical purposes", "Share it after removing the turnover figures"]', 2, 'Statistical confidentiality is unconditional and does not turn on the requester''s intent. Data collected for statistical purposes may not be diverted to regulatory, commercial or personal use.', 'easy', 'APPROVED', 'Collection of Statistics Act 2008'),
('q-066', NULL, 'comp-mgr-003', 'Why is confidentiality treated as a precondition for data quality rather than only as a legal duty?', '["Because it lowers the cost of data processing", "Because it allows a smaller sample to be used", "Because the law prescribes penalties for disclosure", "Because respondents answer truthfully only when they trust that their individual returns cannot be traced back to them"]', 3, 'A breach damages future response rates and the truthfulness of answers, so the harm appears in the estimates themselves and not only in a legal proceeding. Penalties are the enforcement mechanism, not the underlying reason.', 'medium', 'APPROVED', 'UN Fundamental Principles of Official Statistics'),
('q-067', NULL, 'comp-mgr-003', 'An officer holds a substantial shareholding in a company that is a large unit in an industrial survey they supervise. What does integrity require?', '["Disclose the interest and withdraw from decisions concerning that unit", "Continue, provided no confidential information leaves the office", "Sell the shareholding quietly and say nothing", "Nothing, because owning shares is lawful"]', 0, 'A conflict of interest concerns the possibility and the appearance of influence, not proof of misconduct. Disclosure with recusal protects both the officer and the credibility of the statistic, whereas handling it privately leaves no record that the conflict was ever managed.', 'hard', 'APPROVED', 'Central Civil Services Conduct Rules'),
('q-068', NULL, 'comp-mgr-004', 'A department replaces paper schedules with tablet-based data capture. Which factor most often decides whether adoption succeeds?', '["The processing speed of the tablets", "Training and sustained support for field staff, so users can work confidently in the new system", "The number of features built into the application", "The size of the initial hardware order"]', 1, 'Technology failures in government are usually adoption failures. Capable hardware and a rich feature set do not help if investigators lack confidence or have nobody to call when a schedule will not sync.', 'easy', 'APPROVED', 'iGOT Karmayogi Change Management Module'),
('q-069', NULL, 'comp-mgr-004', 'Why is running the paper and digital processes in parallel for one round often preferred to an immediate cutover?', '["It halves the cost of the round", "It removes the need to train staff on the new system", "It allows the outputs of the two processes to be compared, so errors surface while a working fallback still exists", "It shortens the overall duration of the round"]', 2, 'Parallel running costs more and takes longer, and that is precisely the price of the safety it buys. Comparable outputs provide evidence that the new pipeline is correct before the old one is retired.', 'medium', 'APPROVED', 'iGOT Karmayogi Change Management Module'),
('q-070', NULL, 'comp-mgr-004', 'Six months after a new reporting portal launches, most officers still compile reports in spreadsheets and upload the result. What should be examined first?', '["Whether officers should face disciplinary action for non-compliance", "Whether the portal needs additional features", "Whether the training budget should be increased", "Whether the portal''s workflow actually fits how the work is done, since a persistent workaround usually signals a design mismatch"]', 3, 'A widespread workaround is diagnostic information: users have found the portal slower or less capable for a real step in their task. Treating it as an attitude problem conceals the requirement that was missed. More training or more features may still be needed, but they follow the diagnosis rather than replace it.', 'hard', 'APPROVED', 'iGOT Karmayogi Change Management Module'),
('q-071', NULL, 'comp-mgr-005', 'Why must a national statistical release be coordinated with state directorates in advance?', '["Because states supply and validate much of the underlying data, and unreconciled figures would surface as public contradictions", "Because states have the authority to veto the release", "Because central publication rules require an accompanying state press note", "Because states hold the printing contracts"]', 0, 'Coordination is about reconciliation before publication, not permission. Two arms of government publishing different numbers for the same district costs more credibility than a short delay would.', 'easy', 'APPROVED', 'MoSPI State Coordination Guidelines'),
('q-072', NULL, 'comp-mgr-005', 'A line ministry disputes an employment estimate shortly before its release. What is the appropriate handling?', '["Adjust the estimate to the ministry''s preferred figure to avoid conflict", "Examine the methodological basis of the objection, correct the estimate only if an error is established, and record the decision", "Release without acknowledging the objection", "Withdraw the indicator until the ministry agrees"]', 1, 'An objection is a hypothesis to be tested against method, not a negotiation. Changing a figure because of who asked destroys professional independence, while ignoring a substantive methodological point is equally a failure. Documenting the reasoning is what makes the decision defensible afterwards.', 'medium', 'APPROVED', 'MoSPI State Coordination Guidelines'),
('q-073', NULL, 'comp-mgr-005', 'Two departments publish different totals for the same scheme, each drawing on its own administrative records. Which step best resolves the conflict at its root?', '["Publishing the average of the two totals", "Adopting the higher figure as the official number", "Reconciling the definitions, reference periods and coverage behind each figure, then agreeing one source of truth with the differences documented", "Discontinuing both figures until a fresh survey is conducted"]', 2, 'Divergent totals usually reflect different definitions or reference dates rather than arithmetic error. Reconciliation identifies the real difference and lets one series be designated authoritative while the other is explained; averaging or choosing by preference hides the cause and reproduces the problem next cycle.', 'hard', 'APPROVED', 'MoSPI State Coordination Guidelines');

-- Role targets: the expected proficiency a job role demands on each competency.
-- Two contrasting roles are seeded deliberately, because the contrast IS the argument.
-- 62% in Survey Design & Sampling is a real gap for a field survey coordinator running an
-- NSS round (target 80) and comfortably adequate for an establishment officer who never
-- touches sample design (target 35). Score the officer against one global pass mark and
-- "competency gap" collapses into "low score"; score against the role and the same number
-- means two different things. Roles with no rows here fall back to the engine's absolute
-- thresholds, so a missing role degrades the reading instead of breaking it.
-- Keyed on profiles.job_role, which is what CompetencyEngine looks up.
INSERT OR REPLACE INTO role_targets (id, job_role, competency_id, target_score, rationale) VALUES
('rt-001', 'Senior Data Analyst & Field Survey Coordinator', 'comp-stat-001', 75, 'Estimates and their standard errors are produced daily; inference is the core of the role.'),
('rt-002', 'Senior Data Analyst & Field Survey Coordinator', 'comp-stat-002', 80, 'Owns sample design and weight application for an NSS round; the highest bar in the role.'),
('rt-003', 'Senior Data Analyst & Field Survey Coordinator', 'comp-stat-003', 60, 'Consumes national accounts and price series as context rather than compiling them.'),
('rt-004', 'Senior Data Analyst & Field Survey Coordinator', 'comp-stat-004', 75, 'Socio-economic and labour schedules are a primary subject area for this post.'),
('rt-005', 'Senior Data Analyst & Field Survey Coordinator', 'comp-stat-005', 60, 'Rural schedules overlap with the assignment, but crop estimation sits with another division.'),
('rt-006', 'Senior Data Analyst & Field Survey Coordinator', 'comp-stat-006', 55, 'Enterprise surveys are adjacent work; awareness of ASI and IIP concepts is sufficient.'),
('rt-007', 'Senior Data Analyst & Field Survey Coordinator', 'comp-stat-007', 55, 'Supplies data for the National Indicator Framework without owning the reporting.'),
('rt-008', 'Senior Data Analyst & Field Survey Coordinator', 'comp-stat-008', 75, 'Editing, imputation and non-response adjustment decisions are taken in this post.'),
('rt-009', 'Senior Data Analyst & Field Survey Coordinator', 'comp-tech-001', 75, 'Processing and tabulation are performed personally in Python or R.'),
('rt-010', 'Senior Data Analyst & Field Survey Coordinator', 'comp-tech-002', 70, 'Prepares tables, charts and metadata that are published under the division''s name.'),
('rt-011', 'Senior Data Analyst & Field Survey Coordinator', 'comp-tech-003', 70, 'Survey design declarations and weighted estimation are routinely run in Stata or SPSS.'),
('rt-012', 'Senior Data Analyst & Field Survey Coordinator', 'comp-tech-004', 65, 'Extracts and joins unit-level data; needs correct join and null semantics, not schema design.'),
('rt-013', 'Senior Data Analyst & Field Survey Coordinator', 'comp-tech-005', 55, 'Uses administrative sources occasionally; linkage is specialist work elsewhere.'),
('rt-014', 'Senior Data Analyst & Field Survey Coordinator', 'comp-tech-006', 45, 'Should understand overfitting and transparency limits without building models.'),
('rt-015', 'Senior Data Analyst & Field Survey Coordinator', 'comp-gov-001', 70, 'Handles unit-level records containing personal data throughout the round.'),
('rt-016', 'Senior Data Analyst & Field Survey Coordinator', 'comp-gov-002', 50, 'Signs internal submissions; certificate administration is not part of the role.'),
('rt-017', 'Senior Data Analyst & Field Survey Coordinator', 'comp-gov-003', 40, 'Consumes hosted systems; infrastructure decisions sit with the technical division.'),
('rt-018', 'Senior Data Analyst & Field Survey Coordinator', 'comp-gov-004', 45, 'Needs to read an API contract and a code list, not to design the architecture.'),
('rt-019', 'Senior Data Analyst & Field Survey Coordinator', 'comp-gov-005', 60, 'Prepares microdata for release, so disclosure control cannot be delegated blindly.'),
('rt-020', 'Senior Data Analyst & Field Survey Coordinator', 'comp-mgr-001', 60, 'Briefs seniors and drafts release notes; not the public face of the release.'),
('rt-021', 'Senior Data Analyst & Field Survey Coordinator', 'comp-mgr-002', 80, 'Field coordination is half the designation; supervision and quality control are owned here.'),
('rt-022', 'Senior Data Analyst & Field Survey Coordinator', 'comp-mgr-003', 80, 'Direct custody of respondent identity makes confidentiality non-negotiable.'),
('rt-023', 'Senior Data Analyst & Field Survey Coordinator', 'comp-mgr-004', 50, 'Adopts new field systems; does not lead the rollout.'),
('rt-024', 'Senior Data Analyst & Field Survey Coordinator', 'comp-mgr-005', 55, 'Coordinates with state directorates on data, under the division head''s cover.');

-- The contrasting role. Same 24 competencies, a different shape of expectation: statistical
-- and technical bars drop sharply, governance and people-facing bars rise. Ethics stays at 80
-- for both, because respondent confidentiality does not become optional at a lower grade.
INSERT OR REPLACE INTO role_targets (id, job_role, competency_id, target_score, rationale) VALUES
('rt-025', 'Administrative Officer (Establishment)', 'comp-stat-001', 40, 'Reads statistical output; does not produce estimates.'),
('rt-026', 'Administrative Officer (Establishment)', 'comp-stat-002', 35, 'Never touches sample design, so a modest score here is not a gap.'),
('rt-027', 'Administrative Officer (Establishment)', 'comp-stat-003', 35, 'General awareness of headline indicators is enough for this post.'),
('rt-028', 'Administrative Officer (Establishment)', 'comp-stat-004', 35, 'Employment concepts appear in briefs rather than in the officer''s own work.'),
('rt-029', 'Administrative Officer (Establishment)', 'comp-stat-005', 30, 'Outside the functional area of establishment work.'),
('rt-030', 'Administrative Officer (Establishment)', 'comp-stat-006', 30, 'Outside the functional area of establishment work.'),
('rt-031', 'Administrative Officer (Establishment)', 'comp-stat-007', 30, 'SDG reporting is handled by the subject divisions.'),
('rt-032', 'Administrative Officer (Establishment)', 'comp-stat-008', 45, 'Processes records where completeness and revision discipline still matter.'),
('rt-033', 'Administrative Officer (Establishment)', 'comp-tech-001', 35, 'Uses spreadsheets rather than scripted analysis.'),
('rt-034', 'Administrative Officer (Establishment)', 'comp-tech-002', 40, 'Interprets published tables and dashboards prepared by others.'),
('rt-035', 'Administrative Officer (Establishment)', 'comp-tech-003', 30, 'No requirement to run statistical packages.'),
('rt-036', 'Administrative Officer (Establishment)', 'comp-tech-004', 35, 'Queries service records through an interface, not through SQL.'),
('rt-037', 'Administrative Officer (Establishment)', 'comp-tech-005', 30, 'Administrative data integration is not part of the role.'),
('rt-038', 'Administrative Officer (Establishment)', 'comp-tech-006', 25, 'Awareness level only.'),
('rt-039', 'Administrative Officer (Establishment)', 'comp-gov-001', 70, 'Handles service books and personal records of staff throughout the year.'),
('rt-040', 'Administrative Officer (Establishment)', 'comp-gov-002', 65, 'Signs and processes e-office files daily, so certificate discipline is operational here.'),
('rt-041', 'Administrative Officer (Establishment)', 'comp-gov-003', 45, 'Raises and tracks requirements on hosted systems.'),
('rt-042', 'Administrative Officer (Establishment)', 'comp-gov-004', 40, 'Works across departmental systems and feels interoperability failures directly.'),
('rt-043', 'Administrative Officer (Establishment)', 'comp-gov-005', 50, 'Responds to information requests, so sharing classification must be understood.'),
('rt-044', 'Administrative Officer (Establishment)', 'comp-mgr-001', 70, 'Drafting, correspondence and internal communication are the substance of the post.'),
('rt-045', 'Administrative Officer (Establishment)', 'comp-mgr-002', 55, 'Supports survey rounds administratively with logistics and payments.'),
('rt-046', 'Administrative Officer (Establishment)', 'comp-mgr-003', 80, 'Confidentiality and conflict-of-interest duties do not weaken at any grade.'),
('rt-047', 'Administrative Officer (Establishment)', 'comp-mgr-004', 65, 'Establishment functions are usually the first to be digitised, and resistance lands here.'),
('rt-048', 'Administrative Officer (Establishment)', 'comp-mgr-005', 70, 'Continuous coordination across divisions, states and vendors.');

-- Seed Historical Quiz Attempt & Results for Ananya Sharma
INSERT OR REPLACE INTO quiz_attempts (id, user_id, total_questions, correct_answers, overall_score, completed_at) VALUES
('att-001', 'u-official-001', 10, 7, 70.0, '2026-08-20 10:30:00');

INSERT OR REPLACE INTO competency_results (id, attempt_id, competency_id, score, status, priority, evidence) VALUES
('cr-001', 'att-001', 'comp-stat-001', 42.0, 'critical_gap', 1, 'Missed 3 out of 4 questions on sampling errors, design effects, and hypothesis testing.'),
('cr-002', 'att-001', 'comp-stat-002', 55.0, 'critical_gap', 2, 'Struggled with complex survey sampling weights and variance estimation.'),
('cr-003', 'att-001', 'comp-stat-003', 65.0, 'needs_improvement', 3, 'Correctly identified CPI formula but missed base year adjustment concepts.'),
('cr-004', 'att-001', 'comp-tech-001', 88.0, 'strong', 0, 'Demonstrated high proficiency in Python data structures and SQL window functions.'),
('cr-005', 'att-001', 'comp-tech-002', 75.0, 'needs_improvement', 4, 'Good grasp of GIS visualization, basic understanding of SDMX eXchange standards.'),
('cr-006', 'att-001', 'comp-gov-001', 90.0, 'strong', 0, 'Excellent compliance knowledge regarding DPDP Act and Data Privacy rules.'),
('cr-007', 'att-001', 'comp-mgr-001', 85.0, 'strong', 0, 'Solid understanding of Critical Path Method and survey team leadership.');

-- Seed Learning Paths
INSERT OR REPLACE INTO learning_paths (id, user_id, attempt_id, course_id, course_title, competency_id, provider, priority, estimated_duration, status) VALUES
('lp-001', 'u-official-001', 'att-001', 'NSSTA-TPAC-STAT-101', 'Advanced Survey Sampling & Weight Calibration', 'comp-stat-002', 'NSSTA TPAC', 'High', '4 hours', 'IN_PROGRESS'),
('lp-002', 'u-official-001', 'att-001', 'IGOT-STAT-204', 'Statistical Inference & Hypothesis Testing in Practice', 'comp-stat-001', 'iGOT Karmayogi', 'High', '3 hours', 'ASSIGNED'),
('lp-003', 'u-official-001', 'att-001', 'IGOT-ECON-102', 'National Accounts Statistics & Inflation Metrics', 'comp-stat-003', 'iGOT Karmayogi', 'Medium', '2.5 hours', 'ASSIGNED'),
('lp-004', 'u-official-001', 'att-001', 'NSSTA-TECH-301', 'SDMX Metadata Standards & Open Data Publishing', 'comp-tech-002', 'NSSTA TPAC', 'Medium', '2 hours', 'ASSIGNED');
